import { describe, it, expect, vi } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { ViatorClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/health.js';

// A CloudFront WAF refusal (the page Zola served on 2026-10-01). It answers
// 403 like a rejected key, but the key was never evaluated — telling the user
// to re-check VIATOR_API_KEY sends them after the wrong problem.
const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: abc123==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

function clientReturning(res: () => Response) {
  const fetchImpl = vi.fn(async () => res());
  return new ViatorClient({ apiKey: 'K', fetchImpl: fetchImpl as unknown as typeof fetch, sleep: async () => {} });
}

async function healthcheck(client: ViatorClient) {
  const h = await createTestHarness((s) => registerHealthcheckTools(s, client, () => 'K'));
  return parseToolResult<any>(await h.callTool('vt_healthcheck'));
}

describe('CDN/WAF edge blocks', () => {
  it('vt_healthcheck reports a CloudFront 403 block page as edge_blocked, not a rejected key', async () => {
    const client = clientReturning(
      () =>
        new Response(CLOUDFRONT_BLOCK, {
          status: 403,
          headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' },
        }),
    );
    const out = await healthcheck(client);
    expect(out.ok).toBe(false);
    expect(out.error.kind).toBe('edge_blocked');
    expect(out.error.detail).toEqual({ vendor: 'CloudFront' });
    expect(out.hint).not.toMatch(/sandbox/i);
  });

  it('a plain 403 from the API is still reported as a rejected key', async () => {
    const client = clientReturning(
      () => new Response(JSON.stringify({ code: 'UNAUTHORIZED', message: 'Invalid API key' }), { status: 403 }),
    );
    const out = await healthcheck(client);
    expect(out.error.kind).toBe('credential_rejected');
    expect(out.hint).toMatch(/sandbox/i);
  });

  it('tool calls name the edge block instead of blaming the key', async () => {
    const client = clientReturning(() => new Response(CLOUDFRONT_BLOCK, { status: 403 }));
    await expect(client.post('/products/search', {})).rejects.toThrow(/CDN\/WAF \(CloudFront\)/);
  });
});
